set(CMAKE_BUILD_TYPE "Release"  CACHE STRING "" FORCE)

set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS}  -march=armv8-a" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS    "${CMAKE_C_FLAGS}    -march=armv8-a" CACHE STRING "" FORCE)
set(DCMAKE_ASM_FLAGS "${DCMAKE_ASM_FLAGS} -march=armv8-a" CACHE STRING "" FORCE)